typography_spectrum: 0.54717
color:
  brandColors:
    - '#000000'
    - '#244366'
    - '#49739e'
    - '#fefefe'
    - '#b2e4f9'
  brandStrength: 0.5008333618752658
  lightness: 0.625
  saturation: 0.735858557280153
  rhythmicContrast: 0.4783866163343191
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6910035605542362
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: J. Donovan Smith
  email: info@jdonovansmith.com
  url: www.jdonovansmith.com
name: J. Donovan Smith
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About
    id: 275e59b7-0134-445e-beaf-89b690919d22
    type: content
  - name: Photography
    id: e26a0d27-e220-43dd-b966-f86f8458a632
    type: content
favicon: null
title: 'DESIGN, MOTORCYCLES & LIFE'
description: A creative journey through time and space
purpose: []
