name: J. Donovan Smith
favicon: null
layout_spectrum: 0.6910035605542362
typography_spectrum: 0.54717
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#244366'
    - '#49739e'
    - '#fefefe'
    - '#b2e4f9'
  brandStrength: 0.5008333618752658
  lightness: 0.7104904816951603
  saturation: 0.735858557280153
  rhythmicContrast: 0.4783866163343191
purpose: []
