typography_spectrum: 0.54717
color:
  brandColors:
    - '#000000'
    - '#244366'
    - '#49739e'
    - '#fefefe'
    - '#b2e4f9'
  brandStrength: 0.5008333618752658
  lightness: 0.625
  saturation: 0.735858557280153
  rhythmicContrast: 0.4783866163343191
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6910035605542362
analytics:
  google: null
  facebook: null
  twitter: null
name: J. Donovan Smith
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: 'DESIGN, MOTORCYCLES & LIFE'
description: A Creative Endeavorist on a creative journey
purpose: []
